### ISSUE TITLE
`zstandard`/`zstd` dependency can cause QCPortal crashes when bundled elsewhere

### ISSUE THREAD

**Issue by mattwthompson** [conda-forge/qcfractal-feedstock#43]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

```shell
$ mamba create --name qcportal-openeye qcportal openeye-toolkits -c conda-forge -c openeye
...
$ mamba activate qcportal-openeye
$ python -c "from openeye import *; import qcportal"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mattthompson/mambaforge/envs/qcportal-openeye/lib/python3.11/site-packages/qcportal/__init__.py", line 10, in <module>
    from .client import PortalClient
  File "/Users/mattthompson/mambaforge/envs/qcportal-openeye/lib/python3.11/site-packages/qcportal/client.py", line 8, in <module>
    from qcportal.gridoptimization import (
  File "/Users/mattthompson/mambaforge/envs/qcportal-openeye/lib/python3.11/site-packages/qcportal/gridoptimization/__init__.py", line 1, in <module>
    from .dataset_models import (
  File "/Users/mattthompson/mambaforge/envs/qcportal-openeye/lib/python3.11/site-packages/qcportal/gridoptimization/dataset_models.py", line 6, in <module>
    from qcportal.dataset_models import BaseDataset
  File "/Users/mattthompson/mambaforge/envs/qcportal-openeye/lib/python3.11/site-packages/qcportal/dataset_models.py", line 14, in <module>
    from qcportal.dataset_view import DatasetViewWrapper
  File "/Users/mattthompson/mambaforge/envs/qcportal-openeye/lib/python3.11/site-packages/qcportal/dataset_view.py", line 7, in <module>
    import zstandard
  File "/Users/mattthompson/mambaforge/envs/qcportal-openeye/lib/python3.11/site-packages/zstandard/__init__.py", line 39, in <module>
    from .backend_c import *  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: zstd C API versions mismatch; Python bindings were not compiled/linked against expected zstd version (10502 returned by the lib, 10505 hardcoded in zstd headers, 10505 hardcoded in the cext)
```

The conflict might be due to old bundled versions of both the C library and the Python package:

```shell
$ grep zst osx-64_openeye-toolkits-2023.1.1-py39_0/info/about.json                                                                                                                                          10:56:31
    "zstandard 0.18.0 py39hca72f7f_0",
    "zstd 1.5.2 hcb37349_0",
```
Note this does not require a valid OpenEye license.

The workaround AFAICT is to import things in a different order. This does not crash:

```shell
$ python -c "import qcportal; from openeye import *"
```
### Installed packages

```shell
# packages in environment at /Users/mattthompson/mambaforge/envs/qcportal-openeye:
#
# Name                    Version                   Build  Channel
brotli-python             1.1.0           py311ha891d26_1    conda-forge
bzip2                     1.0.8                h93a5062_5    conda-forge
ca-certificates           2023.7.22            hf0a4a13_0    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.16.0          py311h4a08483_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
exceptiongroup            1.1.3              pyhd8ed1ab_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
iniconfig                 2.0.0              pyhd8ed1ab_0    conda-forge
libblas                   3.9.0           19_osxarm64_openblas    conda-forge
libcblas                  3.9.0           19_osxarm64_openblas    conda-forge
libcxx                    16.0.6               h4653b0c_0    conda-forge
libexpat                  2.5.0                hb7217d7_1    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0           13_2_0_hd922786_1    conda-forge
libgfortran5              13.2.0               hf226fd6_1    conda-forge
liblapack                 3.9.0           19_osxarm64_openblas    conda-forge
libopenblas               0.3.24          openmp_hd76b1f2_0    conda-forge
libsqlite                 3.44.0               h091b4b1_0    conda-forge
libzlib                   1.2.13               h53f4e23_5    conda-forge
llvm-openmp               17.0.5               hcd81f8e_0    conda-forge
msgpack-python            1.0.6           py311he4fd1f5_0    conda-forge
ncurses                   6.4                  h463b476_2    conda-forge
numpy                     1.26.0          py311hb8f3215_0    conda-forge
openeye-toolkits          2023.1.1                py311_0    openeye
openssl                   3.1.4                h0d3ecfb_0    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pandas                    2.1.3           py311h6e08293_0    conda-forge
pint                      0.22               pyhd8ed1ab_1    conda-forge
pip                       23.3.1             pyhd8ed1ab_0    conda-forge
pluggy                    1.3.0              pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydantic                  1.10.13         py311h05b510d_1    conda-forge
pyjwt                     2.8.0              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pytest                    7.4.3              pyhd8ed1ab_0    conda-forge
python                    3.11.6          h47c9636_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
python_abi                3.11                    4_cp311    conda-forge
pytz                      2023.3.post1       pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.1           py311heffc1b2_1    conda-forge
qcelemental               0.27.1             pyhd8ed1ab_0    conda-forge
qcportal                  0.51               pyhd8ed1ab_0    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
tabulate                  0.9.0              pyhd8ed1ab_1    conda-forge
tk                        8.6.13               h5083fa2_1    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tqdm                      4.66.1             pyhd8ed1ab_0    conda-forge
typing-extensions         4.8.0                hd8ed1ab_0    conda-forge
typing_extensions         4.8.0              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
urllib3                   2.1.0              pyhd8ed1ab_0    conda-forge
wheel                     0.41.3             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
yaml                      0.2.5                h3422bc3_2    conda-forge
zstandard                 0.22.0          py311h67b91a1_0    conda-forge
zstd                      1.5.5                h4f39d0f_0    conda-forge
```

### Environment info

```shell
active environment : qcportal-openeye
    active env location : /Users/mattthompson/mambaforge/envs/qcportal-openeye
            shell level : 14
       user config file : /Users/mattthompson/.condarc
 populated config files : /Users/mattthompson/.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=arm64
                          __osx=13.0.1=0
                          __unix=0=0
       base environment : /Users/mattthompson/mambaforge  (writable)
      conda av data dir : /Users/mattthompson/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/mattthompson/mambaforge/pkgs
                          /Users/mattthompson/.conda/pkgs
       envs directories : /Users/mattthompson/mambaforge/envs
                          /Users/mattthompson/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.3.1 requests/2.31.0 CPython/3.10.12 Darwin/22.1.0 OSX/13.0.1
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by bennybp** [comment]
I'm not sure what to make of this. We have a pretty plain dependence on `zstandard` and nothing about the underlying implementation.

Does the openeye package have a pinned `zstandard` or `zstd` dependence?

**Comment by mattwthompson** [comment]
I opened this mostly for visibility so that if people run into it the information isn't sequestered to private slack channels. The errors are from the imports, not QCArchive doing anything funky. I'd be shocked if there was a simple fix to this, I certainly don't have a suggestion. For now I've gotten everything to work okay with that workaround.

> Does the openeye package have a pinned `zstandard` or `zstd` dependence?

I don't have visibility into their source code, but the way they package their software is to also bundle a bunch of stuff alongside their toolkits. The versions of these two packages they bundled were more or less up-to-date at the time this version of their package was made. There's supposed to be a release sometime soon and I hope that a new package bundles newer versions of things. (When that comes out, I'll try to remember to check this and close it if it's fixed as I expect.)

It's all a bit confusing to me why this is an issue at all. These packages aren't newly used in the ecosystem, and OpenEye has probably been bundling them for ages as well. I don't really understand how the versions of things bundled within other packages (I might not be using the right language here) affects or does not affect other packages. Here it seems like there's an old `zstd` that gets loaded up into memory from OpenEye's files, and later when QCPortal imports `zstandard` it finds a C mismatch that it spits back out. I guess there was a change in those C bindings within the past year that is backwards-incompatible (but forwards-compatible, importing QCPortal first doesn't cause OpenEye to complain). I found a [similar issue reported](https://github.com/conda-forge/zstandard-feedstock/issues/52), but I don't think pinning QCPortal to an old version is a good idea.

**Comment by mattwthompson** [comment]
Closing this since it's truly not a QCArchive problem - we were able to isolate to simply the `zstandard` import:

With 0.22:

```shell
$ python
Python 3.11.8 | packaged by conda-forge | (main, Feb 16 2024, 20:49:36) [Clang 16.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import zstandard
>>> from openeye import oechem
>>>
$ python
Python 3.11.8 | packaged by conda-forge | (main, Feb 16 2024, 20:49:36) [Clang 16.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from openeye import oechem
>>> import zstandard
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mattthompson/micromamba/envs/qcsubmit-test-basic/lib/python3.11/site-packages/zstandard/__init__.py", line 39, in <module>
    from .backend_c import *  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: zstd C API versions mismatch; Python bindings were not compiled/linked against expected zstd version (10502 returned by the lib, 10505 hardcoded in zstd headers, 10505 hardcoded in the cext)
```
The same runs without error on 0.18

**Comment by mattwthompson** [comment]
Better solution: `PYTHON_ZSTANDARD_IMPORT_POLICY='cffi_fallback'`

https://github.com/MolSSI/QCFractal/pull/827#issuecomment-2088711453
